<?php
$state = $this->getContent();
?>
<?php if ($state->count()): ?>

 <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map_canvas { height: 100% }
    </style>
    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBcxNOJoFzOE_EW1ZyDQyfB5EyEylFK_CE" >
    </script>

<div class="container-fluid">
<h2><strong>Pontos de Venda</strong></h2>
<br>
<br>
<br>

<?php 
	foreach ($state as $num => $key) {
			echo '<div class="row">';
			echo '<div class="col-md-3">';
			echo '<div id="map_canvas'.$num.'" style="width:200px; height:200px"></div>';
			echo '</div>';
			echo '<div class="col-md-9">';
			echo "<h3>{$key['title']}</h3>";
			echo "{$key['address']} {$key['postcode']}<br>";
			echo "{$key['city']} - {$key['state']}";
			echo '</div></div>';
			
?>
	<script type="text/javascript">
       function initialize() {
                  var image = 'images/icone-local.png'; //ICONE
                  var endereco = '<?=$key['address'].' '.$key['city']?>'; // ENDEREÇO DO MAPA
                  var mapOptions = {
                    zoom: 13,
                    scrollwheel:false,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                  };
                  var map = new google.maps.Map(document.getElementById('map_canvas<?=$num?>'), mapOptions);
                  geocoder = new google.maps.Geocoder();
                    geocoder.geocode({'address':endereco}, function(results, status){
                        if( status = google.maps.GeocoderStatus.OK){
                            latlng = results[0].geometry.location;
                            var marker = new google.maps.Marker({
                                position: latlng,
                                map: map,
                                //icon: image,
                                title: 'Teste' //NOME DA UNIDADE
                            });
                            map.setCenter(latlng);
                        }
                    });
          
                }
                google.maps.event.addDomListener(window, 'load', initialize);

    </script>
<?php
	echo '<div class="clearfix"></div>';
	echo '<br><hr/><br/>';
	}
?>

</div>

<?php else: ?>
	<h2>Não há pontos de venda cadastrados</h2>
<?php endif ?>


    