<?php
$state = $this->getContent();
?>
<h2>
<?php echo (!$state['error']) ? $state['title'] : $state['error'] ?>
</h2>
<div id="map"></div>
<?php if (!$state['error']): ?>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAJnO8_hu8aA-6miQE9aly3qcPwHpSFVY0&callback=initMap"></script>
<script>
	function initMap() {
		var map = new google.maps.Map(document.getElementById('map'), {
			zoom: 8,
			center: new google.maps.LatLng(<?php echo $state['latitude'] ?>, <?php echo $state['longitude'] ?>),
		});

		var infowindow = new google.maps.InfoWindow({});
		var image = {
				url: '<?php echo Mage::getBaseUrl('media').'/theme/'.Mage::getStoreConfig('store/test/logo',Mage::app()->getStore()); ?>',
				scaledSize: new google.maps.Size(30, 30)
			};
		var marker = new google.maps.Marker({
			position: new google.maps.LatLng(<?php echo $state['latitude'] ?>, <?php echo $state['longitude'] ?>),
			map: map,
			<?php echo file_exists(Mage::getBaseDir('media').'/theme/'.Mage::getStoreConfig('store/test/logo',Mage::app()->getStore())) ? "
				icon: image" : "" ?>
		});

		google.maps.event.addListener(marker, 'click', function (marker) {
			return function () {
				infowindow.setContent('<?php echo $state['title'] ?>');
				infowindow.open(map, marker);
			}
		});
	}
</script>
<?php endif ?>